image: maven:3.6.3-jdk-11

stages:
    - build

cache:
    paths:
        - .m2/repository

build:
    stage: build
    script:
        - mvn package -DskipTests
        - cp target/*.war /target/
    artifacts:
        paths:
            - target/*.war
    tags:
        - rapla
