image: maven:3.6.1-jdk-8

stages:
    - build

cache:
    paths:
        - .m2/repository

build:
    stage: build
    script:
        - mvn package -DskipTests
    artifacts:
        paths:
            - target/*.war
