image: maven:3.6.3-jdk-11

stages:
    - build

cache:
    paths:
        - .m2/repository

build:
    stage: build
    script:
        - mvn package -DskipTests
    artifacts:
        paths:
            - target/*.war
    tags:
        - rapla

docker_build:
    stage: docker_build
    script:
        - docker image build -t .
    tags:
        - rapla
