stages:
    # - maven_build
    # - rapla_image_build
    - deploy

cache:
    paths:
        - .m2/repository

maven_build:
    stage: maven_build
    image: maven:3.6.3-jdk-11
    script:
        - mvn package -DskipTests
    artifacts:
        paths:
            - target/*.war
    tags:
        - rapla

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/vm_ci:$CI_COMMIT_REF_NAME"
  DEPLOY_USER: "ubuntu"
  DEPLOY_HOST: "193.196.55.85"

rapla_image_build:
  stage: rapla_image_build
  image: docker:24.0.5
  services:
    - name: docker:24.0.5-dind
      alias: docker
  script:
    - docker info
    - docker build -t $IMAGE_NAME .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_NAME
  tags:
    - rapla

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh-client
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "docker pull $IMAGE_NAME"
    - ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "docker run -d -p 8051:8051 --name rapla_container $IMAGE_NAME"
  tags:
    - deploy