stages:
    # - maven_build
    # - rapla_image_build
    - deploy

cache:
    paths:
        - .m2/repository
variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  IMAGE_NAME: "$CI_REGISTRY_IMAGE/vm_ci:$CI_COMMIT_REF_NAME"
  DEPLOY_USER: "ubuntu"
  DEPLOY_HOST: "193.196.55.85"


# maven_build:
#     stage: maven_build
#     image: maven:3.6.3-jdk-11
#     script:
#         - mvn package -DskipTests
#     artifacts:
#         paths:
#             - target/*.war
#     tags:
#         - rapla

# rapla_image_build:
#   stage: rapla_image_build
#   image: docker:24.0.5
#   services:
#     - name: docker:24.0.5-dind
#       alias: docker
#   script:
#     - docker info
#     - docker build -t $IMAGE_NAME .
#     - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
#     - docker push $IMAGE_NAME
#   tags:
#     - rapla

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - echo "$SSH_PRIVATE_KEY"
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
  script:
    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY"
    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "sudo docker pull $IMAGE_NAME"
    - ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "sudo docker run -d -p 8080:8080 --name rapla_container $IMAGE_NAME"
  tags:
        - rapla