stages:
    # - build
    - docker_build

cache:
    paths:
        - .m2/repository

# build:
#     stage: build
# image: maven:3.6.3-jdk-11
#     script:
#         - mvn package -DskipTests
#     artifacts:
#         paths:
#             - target/*.war
#     tags:
#         - rapla


docker_build:
    stage: docker_build
    image: docker:24.0.5
    services:
        - name: docker:24.0.5-dind
          alias: docker
    variables:
        DOCKER_HOST: tcp://docker:2375
        DOCKER_TLS_CERTDIR: ""
    script:
        - docker info
        - docker image build -t rapla .
    tags:
        - rapla
